//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace CustomerSkin.Properties {
    
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomerSkin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bg_KeyBoard {
            get {
                object obj = ResourceManager.GetObject("bg_KeyBoard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap btn_mousedown {
            get {
                object obj = ResourceManager.GetObject("btn_mousedown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap btn_mousehover {
            get {
                object obj = ResourceManager.GetObject("btn_mousehover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap keyboard_btn_close {
            get {
                object obj = ResourceManager.GetObject("keyboard_btn_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap keyboard_btn_mousedown {
            get {
                object obj = ResourceManager.GetObject("keyboard_btn_mousedown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap keyboard_btn_mousehover {
            get {
                object obj = ResourceManager.GetObject("keyboard_btn_mousehover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap keyborad_normal {
            get {
                object obj = ResourceManager.GetObject("keyborad_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap pagearrow_down {
            get {
                object obj = ResourceManager.GetObject("pagearrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap pagearrow_hover {
            get {
                object obj = ResourceManager.GetObject("pagearrow_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap tab_close_normal {
            get {
                object obj = ResourceManager.GetObject("tab_close_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap tab_close_over {
            get {
                object obj = ResourceManager.GetObject("tab_close_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap tabpage_down {
            get {
                object obj = ResourceManager.GetObject("tabpage_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap tabpage_hover {
            get {
                object obj = ResourceManager.GetObject("tabpage_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap textbox_mousedown {
            get {
                object obj = ResourceManager.GetObject("textbox_mousedown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap textbox_normal {
            get {
                object obj = ResourceManager.GetObject("textbox_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap alarm
        {
            get
            {
                object obj = ResourceManager.GetObject("alarm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        
        public static System.Drawing.Bitmap dialog_close
        {
            get
            {
                object obj = ResourceManager.GetObject("dialog_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap help
        {
            get
            {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap loading
        {
            get
            {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //success
        public static System.Drawing.Bitmap success
        {
            get
            {
                object obj = ResourceManager.GetObject("success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //warning
        public static System.Drawing.Bitmap warning
        {
            get
            {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //error
        public static System.Drawing.Bitmap error
        {
            get
            {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        //tips
        public static System.Drawing.Bitmap tips
        {
            get
            {
                object obj = ResourceManager.GetObject("tips", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //list_add
        public static System.Drawing.Bitmap list_add
        {
            get
            {
                object obj = ResourceManager.GetObject("list_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //list_subtract
        public static System.Drawing.Bitmap list_subtract
        {
            get
            {
                object obj = ResourceManager.GetObject("list_subtract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //sanjiao1

        public static System.Drawing.Bitmap sanjiao1
        {
            get
            {
                object obj = ResourceManager.GetObject("sanjiao1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap sanjiao2
        {
            get
            {
                object obj = ResourceManager.GetObject("sanjiao2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //radioButton0
        public static System.Drawing.Bitmap radioButton0
        {
            get
            {
                object obj = ResourceManager.GetObject("radioButton0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap radioButton1
        {
            get
            {
                object obj = ResourceManager.GetObject("radioButton1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap radioButton10
        {
            get
            {
                object obj = ResourceManager.GetObject("radioButton10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap radioButton00
        {
            get
            {
                object obj = ResourceManager.GetObject("radioButton00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //checkbox0

        public static System.Drawing.Bitmap checkbox0
        {
            get
            {
                object obj = ResourceManager.GetObject("checkbox0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap checkbox1
        {
            get
            {
                object obj = ResourceManager.GetObject("checkbox1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap checkbox10
        {
            get
            {
                object obj = ResourceManager.GetObject("checkbox10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap checkbox00
        {
            get
            {
                object obj = ResourceManager.GetObject("checkbox00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        //back
        public static System.Drawing.Bitmap back
        {
            get
            {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        //left
        public static System.Drawing.Bitmap left
        {
            get
            {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        //right
        public static System.Drawing.Bitmap right
        {
            get
            {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        //first
        public static System.Drawing.Bitmap first
        {
            get
            {
                object obj = ResourceManager.GetObject("first", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //end
        public static System.Drawing.Bitmap end
        {
            get
            {
                object obj = ResourceManager.GetObject("end", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        //chevron_right
        public static System.Drawing.Bitmap chevron_right
        {
            get
            {
                object obj = ResourceManager.GetObject("chevron_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //chevron_left
        public static System.Drawing.Bitmap chevron_left
        {
            get
            {
                object obj = ResourceManager.GetObject("chevron_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        //qty_delete
        public static System.Drawing.Bitmap qty_delete
        {
            get
            {
                object obj = ResourceManager.GetObject("qty_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        //ComboBox

        public static System.Drawing.Bitmap ComboBox
        {
            get
            {
                object obj = ResourceManager.GetObject("ComboBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        //more1
        public static System.Drawing.Bitmap more1
        {
            get
            {
                object obj = ResourceManager.GetObject("more1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        //ic_remove_black_18dp
        public static System.Drawing.Bitmap ic_remove_black_18dp
        {
            get
            {
                object obj = ResourceManager.GetObject("ic_remove_black_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        //ic_search_black_24dp
        public static System.Drawing.Bitmap ic_search_black_24dp
        {
            get
            {
                object obj = ResourceManager.GetObject("ic_search_black_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        //ic_add_black_18dp
        public static System.Drawing.Bitmap ic_add_black_18dp
        {
            get
            {
                object obj = ResourceManager.GetObject("ic_add_black_18dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //datetLeft
        public static System.Drawing.Bitmap datetLeft
        {
            get
            {
                object obj = ResourceManager.GetObject("datetLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap dateRight
        {
            get
            {
                object obj = ResourceManager.GetObject("dateRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //caret_down
        public static System.Drawing.Bitmap caret_down
        {
            get
            {
                object obj = ResourceManager.GetObject("caret_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap caret_right
        {
            get
            {
                object obj = ResourceManager.GetObject("caret_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //keyboard
        public static System.Drawing.Bitmap keyboard
        {
            get
            {
                object obj = ResourceManager.GetObject("keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        //keyboard_bs
        public static System.Drawing.Bitmap keyboard_bs
        {
            get
            {
                object obj = ResourceManager.GetObject("keyboard_bs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        //input_clear
        public static System.Drawing.Bitmap input_clear
        {
            get
            {
                object obj = ResourceManager.GetObject("input_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
